b1: 0.5
b2: 0.99
batch_size: 1
channels: 3
checkpoint_interval: 1
dataset_name: GTA
decay_epoch: 100
img_height: 1052
img_width: 1916
load_model: true
lr: 0.0002
n_cpu: 4
n_epochs: 100
sample_interval: 25